import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Lightroom Preset Generator",
  description: "Upload a photo, get a tailored Lightroom Classic preset (.xmp) generated by Claude.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
